/**
 * Selector Collector Content Script
 *
 * SG-046: 选择器采集助手
 * Activates on user request, highlights elements on hover,
 * captures CSS selector using priority chain, copies to clipboard.
 *
 * Priority chain: data-testid > data-test > aria-label > role+text > name > id > class > CSS path
 */

import type { PlasmoCSConfig } from 'plasmo';

export const config: PlasmoCSConfig = {
  matches: ['<all_urls>'],
  run_at: 'document_idle',
  world: 'ISOLATED',
};

let active = false;
let highlightOverlay: HTMLDivElement | null = null;
let previewTooltip: HTMLDivElement | null = null;
let panelContainer: HTMLDivElement | null = null;

// ====== Selector Generation ======

function generateSelector(el: Element): string {
  if (el.id) {
    return `#${el.id}`;
  }

  const testId = el.getAttribute('data-testid');
  if (testId) {
    return `[data-testid="${testId}"]`;
  }

  const dataTest = el.getAttribute('data-test');
  if (dataTest) {
    return `[data-test="${dataTest}"]`;
  }

  const ariaLabel = el.getAttribute('aria-label');
  if (ariaLabel) {
    const tag = el.tagName.toLowerCase();
    return `${tag}[aria-label="${ariaLabel}"]`;
  }

  const role = el.getAttribute('role');
  if (role) {
    const text = (el.textContent ?? '').trim().slice(0, 30);
    const tag = el.tagName.toLowerCase();
    if (text) {
      return `${tag}[role="${role}"] >> text="${text}"`;
    }
    return `${tag}[role="${role}"]`;
  }

  const name = el.getAttribute('name');
  if (name) {
    return `[name="${name}"]`;
  }

  const className = el.getAttribute('class');
  if (className) {
    const classes = className.split(/\s+/).filter(Boolean);
    if (classes.length > 0) {
      const tag = el.tagName.toLowerCase();
      const classSelector = classes.map((c) => `.${CSS.escape(c)}`).join('');
      return `${tag}${classSelector}`;
    }
  }

  return buildCssPath(el);
}

function buildCssPath(el: Element): string {
  const parts: string[] = [];
  let current: Element | null = el;

  while (current && current !== document.body && current !== document.documentElement) {
    let selector = current.tagName.toLowerCase();

    if (current.id) {
      selector = `#${CSS.escape(current.id)}`;
      parts.unshift(selector);
      break;
    }

    const parent = current.parentElement;
    if (parent) {
      const siblings = Array.from(parent.children).filter(
        (child) => child.tagName === current!.tagName,
      );
      if (siblings.length > 1) {
        const index = siblings.indexOf(current) + 1;
        selector += `:nth-of-type(${index})`;
      }
    }

    parts.unshift(selector);
    current = current.parentElement;
  }

  return parts.join(' > ');
}

function generateAlternativeSelectors(el: Element): string[] {
  const alternatives: string[] = [];
  const tag = el.tagName.toLowerCase();

  if (el.id) {
    alternatives.push(`#${el.id}`);
  }

  const testId = el.getAttribute('data-testid');
  if (testId) {
    alternatives.push(`[data-testid="${testId}"]`);
  }

  const className = el.getAttribute('class');
  if (className) {
    const classes = className.split(/\s+/).filter(Boolean);
    if (classes.length > 0) {
      alternatives.push(`${tag}${classes.map((c) => `.${CSS.escape(c)}`).join('')}`);
    }
  }

  const text = (el.textContent ?? '').trim();
  if (text && text.length < 50) {
    alternatives.push(`${tag}:has-text("${text.slice(0, 30)}")`);
  }

  return [...new Set(alternatives)];
}

function calculateStabilityScore(el: Element): number {
  let score = 50;

  if (el.id) score += 30;
  if (el.getAttribute('data-testid')) score += 25;
  if (el.getAttribute('data-test')) score += 20;
  if (el.getAttribute('aria-label')) score += 15;
  if (el.getAttribute('role')) score += 10;
  if (el.getAttribute('name')) score += 15;

  const className = el.getAttribute('class');
  if (className) {
    const autoGenerated = /\b(col-|row-|css-|sc-|styled-|tw-)/.test(className);
    if (autoGenerated) score -= 10;
    else score += 5;
  }

  return Math.max(0, Math.min(100, score));
}

// ====== UI ======

function createHighlightOverlay(): HTMLDivElement {
  const overlay = document.createElement('div');
  overlay.style.cssText = `
    position: absolute;
    pointer-events: none;
    z-index: 2147483647;
    border: 2px solid #3b82f6;
    background: rgba(59, 130, 246, 0.1);
    transition: all 0.1s ease;
    border-radius: 2px;
  `;
  document.body.appendChild(overlay);
  return overlay;
}

function createPreviewTooltip(): HTMLDivElement {
  const tooltip = document.createElement('div');
  tooltip.style.cssText = `
    position: absolute;
    z-index: 2147483647;
    background: #1e293b;
    color: #e2e8f0;
    padding: 6px 10px;
    border-radius: 6px;
    font-family: 'SF Mono', 'Fira Code', monospace;
    font-size: 12px;
    max-width: 400px;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    pointer-events: none;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.3);
    transition: opacity 0.15s ease;
  `;
  document.body.appendChild(tooltip);
  return tooltip;
}

function showHighlight(el: Element): void {
  const rect = el.getBoundingClientRect();
  const scrollX = window.scrollX;
  const scrollY = window.scrollY;

  highlightOverlay!.style.display = 'block';
  highlightOverlay!.style.left = `${rect.left + scrollX}px`;
  highlightOverlay!.style.top = `${rect.top + scrollY}px`;
  highlightOverlay!.style.width = `${rect.width}px`;
  highlightOverlay!.style.height = `${rect.height}px`;

  const selector = generateSelector(el);
  previewTooltip!.textContent = selector;
  previewTooltip!.style.display = 'block';

  const tooltipX = rect.left + scrollX;
  const tooltipY = rect.top + scrollY - 32;
  previewTooltip!.style.left = `${Math.max(0, tooltipX)}px`;
  previewTooltip!.style.top = `${Math.max(0, tooltipY)}px`;
}

function hideHighlight(): void {
  if (highlightOverlay) highlightOverlay.style.display = 'none';
  if (previewTooltip) previewTooltip.style.display = 'none';
}

function showPanel(el: Element): void {
  removePanel();

  const selector = generateSelector(el);
  const alternatives = generateAlternativeSelectors(el);
  const stability = calculateStabilityScore(el);
  const matchCount = document.querySelectorAll(selector).length;

  panelContainer = document.createElement('div');
  panelContainer.style.cssText = `
    position: fixed;
    bottom: 20px;
    right: 20px;
    z-index: 2147483647;
    background: #ffffff;
    border: 1px solid #e2e8f0;
    border-radius: 12px;
    box-shadow: 0 8px 32px rgba(0, 0, 0, 0.15);
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
    font-size: 14px;
    color: #1e293b;
    width: 380px;
    max-height: 500px;
    overflow-y: auto;
    line-height: 1.5;
  `;

  const stabilityColor = stability >= 80 ? '#22c55e' : stability >= 50 ? '#f59e0b' : '#ef4444';

  panelContainer.innerHTML = `
    <div style="padding: 16px; border-bottom: 1px solid #f1f5f9; display: flex; align-items: center; justify-content: space-between;">
      <div style="font-weight: 600; font-size: 15px;">选择器采集</div>
      <button id="sg-sc-close" style="background: none; border: none; cursor: pointer; font-size: 18px; color: #94a3b8; padding: 4px 8px;">✕</button>
    </div>
    <div style="padding: 16px;">
      <div style="margin-bottom: 12px;">
        <div style="font-size: 12px; color: #64748b; margin-bottom: 4px; text-transform: uppercase; letter-spacing: 0.5px;">元素</div>
        <div style="font-size: 13px; color: #475569;">&lt;${el.tagName.toLowerCase()}&gt; ${el.getAttribute('class') ? `.${(el.getAttribute('class') ?? '').split(/\s+/)[0]}` : ''}</div>
      </div>
      <div style="margin-bottom: 12px;">
        <div style="font-size: 12px; color: #64748b; margin-bottom: 4px; text-transform: uppercase; letter-spacing: 0.5px;">选择器</div>
        <div id="sg-sc-selector" style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px 12px; font-family: 'SF Mono', 'Fira Code', monospace; font-size: 12px; word-break: break-all; cursor: pointer;" title="点击复制">${selector}</div>
      </div>
      <div style="display: flex; gap: 16px; margin-bottom: 12px;">
        <div>
          <div style="font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px;">稳定性</div>
          <div style="font-size: 20px; font-weight: 700; color: ${stabilityColor};">${stability}</div>
        </div>
        <div>
          <div style="font-size: 12px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px;">匹配数</div>
          <div style="font-size: 20px; font-weight: 700; color: ${matchCount === 1 ? '#22c55e' : '#f59e0b'};">${matchCount}</div>
        </div>
      </div>
      ${
        alternatives.length > 1
          ? `
        <div style="margin-bottom: 12px;">
          <div style="font-size: 12px; color: #64748b; margin-bottom: 4px; text-transform: uppercase; letter-spacing: 0.5px;">候选选择器</div>
          ${alternatives
            .slice(0, 5)
            .map(
              (alt) => `
            <div class="sg-sc-alt" data-selector="${alt}" style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 4px; padding: 4px 8px; margin-bottom: 4px; font-family: 'SF Mono', 'Fira Code', monospace; font-size: 11px; word-break: break-all; cursor: pointer;">${alt}</div>
          `,
            )
            .join('')}
        </div>
      `
          : ''
      }
      <div style="display: flex; gap: 8px;">
        <button id="sg-sc-copy" style="flex: 1; background: #3b82f6; color: white; border: none; border-radius: 6px; padding: 8px 16px; font-size: 13px; font-weight: 500; cursor: pointer;">复制选择器</button>
        <button id="sg-sc-cancel" style="background: #f1f5f9; color: #475569; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px 16px; font-size: 13px; cursor: pointer;">取消</button>
      </div>
    </div>
  `;

  document.body.appendChild(panelContainer);

  // Event listeners
  const closeBtn = panelContainer.querySelector('#sg-sc-close')!;
  closeBtn.addEventListener('click', deactivate);

  const copyBtn = panelContainer.querySelector('#sg-sc-copy')! as HTMLElement;
  copyBtn.addEventListener('click', () => {
    navigator.clipboard.writeText(selector).then(() => {
      copyBtn.textContent = '已复制 ✓';
      copyBtn.style.background = '#22c55e';
      setTimeout(() => {
        copyBtn.textContent = '复制选择器';
        copyBtn.style.background = '#3b82f6';
      }, 1500);
    });
    sendSelectorToBackground(selector, el);
  });

  const selectorBox = panelContainer.querySelector('#sg-sc-selector')! as HTMLElement;
  selectorBox.addEventListener('click', () => {
    navigator.clipboard.writeText(selector);
    selectorBox.style.background = '#dcfce7';
    setTimeout(() => {
      selectorBox.style.background = '#f8fafc';
    }, 500);
  });

  const cancelBtn = panelContainer.querySelector('#sg-sc-cancel')!;
  cancelBtn.addEventListener('click', deactivate);

  const altSelectors = panelContainer.querySelectorAll('.sg-sc-alt');
  altSelectors.forEach((altEl) => {
    altEl.addEventListener('click', () => {
      const altSelector = altEl.getAttribute('data-selector')!;
      navigator.clipboard.writeText(altSelector);
      sendSelectorToBackground(altSelector, el);
      deactivate();
    });
  });
}

function removePanel(): void {
  panelContainer?.remove();
  panelContainer = null;
}

function sendSelectorToBackground(selector: string, el: Element): void {
  try {
    chrome.runtime.sendMessage({
      type: 'SELECTOR_CAPTURED',
      payload: {
        selector,
        tagName: el.tagName.toLowerCase(),
        className: el.getAttribute('class') ?? '',
        id: el.id ?? '',
        text: (el.textContent ?? '').trim().slice(0, 100),
        url: location.href,
        stabilityScore: calculateStabilityScore(el),
        matchCount: document.querySelectorAll(selector).length,
      },
    });
  } catch {
    // Background not available
  }
}

// ====== Event Handlers ======

function onMouseOver(e: MouseEvent): void {
  if (!active) return;
  const target = e.target as Element;
  if (!target || target === document.body || target === document.documentElement) return;
  if (panelContainer?.contains(target)) return;

  showHighlight(target);
}

function onMouseOut(e: MouseEvent): void {
  if (!active) return;
  const related = e.relatedTarget as Element | null;
  if (related && panelContainer?.contains(related)) return;
  hideHighlight();
}

function onClick(e: MouseEvent): void {
  if (!active) return;
  e.preventDefault();
  e.stopPropagation();

  const target = e.target as Element;
  if (!target || target === document.body || target === document.documentElement) return;
  if (panelContainer?.contains(target)) return;

  hideHighlight();
  showPanel(target);
  deactivate();
}

function onKeyDown(e: KeyboardEvent): void {
  if (e.key === 'Escape' && active) {
    deactivate();
  }
}

function onContextMenu(e: MouseEvent): void {
  if (active) {
    e.preventDefault();
    deactivate();
  }
}

// ====== Activation ======

function activate(): void {
  if (active) return;
  active = true;

  highlightOverlay = createHighlightOverlay();
  previewTooltip = createPreviewTooltip();

  document.addEventListener('mouseover', onMouseOver, true);
  document.addEventListener('mouseout', onMouseOut, true);
  document.addEventListener('click', onClick, true);
  document.addEventListener('keydown', onKeyDown, true);
  document.addEventListener('contextmenu', onContextMenu, true);

  document.body.style.cursor = 'crosshair';
}

function deactivate(): void {
  if (!active) return;
  active = false;

  hideHighlight();
  removePanel();

  highlightOverlay?.remove();
  highlightOverlay = null;
  previewTooltip?.remove();
  previewTooltip = null;

  document.removeEventListener('mouseover', onMouseOver, true);
  document.removeEventListener('mouseout', onMouseOut, true);
  document.removeEventListener('click', onClick, true);
  document.removeEventListener('keydown', onKeyDown, true);
  document.removeEventListener('contextmenu', onContextMenu, true);

  document.body.style.cursor = '';
}

// ====== Message Listener ======

chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {
  if (message.type === 'ACTIVATE_SELECTOR_COLLECTOR') {
    activate();
    sendResponse({ ok: true });
    return true;
  }
  if (message.type === 'DEACTIVATE_SELECTOR_COLLECTOR') {
    deactivate();
    sendResponse({ ok: true });
    return true;
  }
  return false;
});

export {};
